name: life-gdp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.16
  - pandas
  - numpy
  - matplotlib
  - pathlib
  - ipykernel
prefix: /home/dracdarktime/miniconda3/envs/life-gdp
